root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/api"
delay = 1000
exclude_dir = ["tmp", "vendor", "docs"]
include_ext = ["go", "tpl", "tmpl"]
kill_delay = "0s"
log = "build-errors.log"

[log]
time = true